# vi-style copy mode
setw -g mode-keys vi

# Display / behaviour
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 10000
set -sg escape-time 0
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
